default:
  image: python:3.11.3-bullseye
  cache:
    paths:
      - .cache/pip
      - .venv/
      - .cache/pre-commit
  before_script:
    # Fix Unistra GitLab Docker runner permission issues
    - export RUNNER_USER=$(ls -ld .git/ | awk '{print $3}')
    - mkdir -p .cache/pre-commit/ .venv/ .cache/pip/
    - chown -R $(whoami) .
    ## Install packages
    - python --version ; pip --version # For debugging
    - python -m venv .venv/
    - source .venv/bin/activate
    - pip install -r requirements.txt
  after_script:
    # Fix Unistra GitLab Docker runner permission issues
    - chown -fR "$RUNNER_USER" .cache/pre-commit/ .venv/ .cache/pip/
stages:
  - test
  - deploy
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  RELEASE_TAG: '/^v\d+\.\d+\.\d+\.*$/'
test:
  stage: test
  dependencies: []
  script:
    - pre-commit run -a
  rules:
    - if: $CI_COMMIT_BRANCH
  allow_failure: true
  tags:
    - kubernetes
